workflows:
  expo_build:
    name: Expo Build (Android & iOS)
    max_build_duration: 60
    environment:
      vars:
        EXPO_TOKEN: $EXPO_TOKEN   # برای login خودکار Expo
      node: latest
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Login to Expo
        script: npx expo login --token $EXPO_TOKEN
      - name: Build Android APK
        script: npx expo build:android -t apk --non-interactive
      - name: Build Android AAB
        script: npx expo build:android -t app-bundle --non-interactive
      - name: Build iOS IPA
        script: npx expo build:ios --non-interactive
    artifacts:
      - dist/*.apk
      - dist/*.aab
      - dist/*.ipa
